# Disable sound
enable_audio_bell no

# Cursor animations
# Makes the cursor move to the destined place, instead of disappearing in one
# place and appearing on another
cursor_trail 1
cursor_trail_decay 0.1 0.2

# Set the allowed layouts and they order
# Currently allowing all layouts and setting "grid" as the default one (first
# one in the list)
enabled_layouts Grid, Fat, Horizontal, Splits, Stack, Tall, Vertical

# Make it ask for confirmation before closing a window with a running program.
# The ignore-shell part makes it do not ask when no program is running (just the
# shell prompt)
map ctrl+shift+w close_window_with_confirmation ignore-shell

# Move focus to the neighboring window
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
