enable_audio_bell no
cursor_trail 1
cursor_trail_decay 0.1 0.2
enabled_layouts Grid, Fat, Horizontal, Splits, Stack, Tall, Vertical

# Move focus to the neighboring window
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
