# Disable sound
enable_audio_bell no

# Cursor animations
# Makes the cursor move to the destined place, instead of disappearing in one
# place and appearing on another
cursor_trail 1
cursor_trail_decay 0.1 0.2

# Set the allowed layouts and they order
enabled_layouts Stack, Grid

# Make it ask for confirmation before closing a window with a running program.
# The ignore-shell part makes it do not ask when no program is running (just the
# shell prompt)
map ctrl+shift+w close_window_with_confirmation ignore-shell

# Move focus to the neighboring window
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

# Map to open a new window in the same cwd as the current one
map ctrl+shift+n launch --type=os-window --cwd=current

# Set nvim as default pager
scrollback_pager nvim --cmd "set eventignore=FileType" -c "nnoremap q ZQ" -c "call nvim_open_term(0, {})" -c "set nomodified nolist number relativenumber" -c "$" -

# BEGIN_KITTY_THEME
include mocha.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='Atkinson Mono NF' postscript_name=AtkinsonMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
