# Central ignore list for aconfmgr
# =======================
# This file declares filesystem paths that aconfmgr will ignore when collecting
# system and user configuration. Transient files, caches, large user-data folders and
# machine-specific artifacts are excluded so the configuration repo stays
# focused on reproducible settings rather than runtime state.

# This is the redefinition of the initial ignore path list from the aconfmgr source code.
# I have comented out "home". This includes it on the configuration
ignore_paths=(
    '/dev'
    # '/home'
    '/media'
    '/mnt'
    '/proc'
    '/root'
    '/run'
    '/sys'
    '/tmp'
    # '/var/.updated'
    '/var/cache'
    # '/var/lib'
    # '/var/lock'
    # '/var/log'
    # '/var/spool'
)

# Home
# ====

# Do not ignore icons nor fonts in ".local/share/" if you have manully put them there. It is ok to ignore if it comes from packages
IgnorePath "/etc/fuse.conf"
IgnorePath "/etc/texmf/web2c/fmtutil.cnf.pacsave"
IgnorePath "/home/davi/.agents/skills"
IgnorePath "/home/davi/.bash_history"
IgnorePath "/home/davi/.bash_history-*.tmp"
IgnorePath "/home/davi/.cache/*"
IgnorePath "/home/davi/.cargo/*"
IgnorePath "/home/davi/.claude-hfi/*"
IgnorePath "/home/davi/.claude/*"
IgnorePath "/home/davi/.config/Code/*"
IgnorePath "/home/davi/.config/Code/logs/*"
IgnorePath "/home/davi/.config/GIMP"
IgnorePath "/home/davi/.config/GIMP/*"
IgnorePath "/home/davi/.config/QtProject.conf"
IgnorePath "/home/davi/.config/QtProject/*"
IgnorePath "/home/davi/.config/aconfmgr/*"
IgnorePath "/home/davi/.config/dconf/*"
IgnorePath "/home/davi/.config/fltk.org"
IgnorePath "/home/davi/.config/git/ignore"
IgnorePath "/home/davi/.config/github-copilot/*"
IgnorePath "/home/davi/.config/go"
IgnorePath "/home/davi/.config/hypr/.git"
IgnorePath "/home/davi/.config/kdeconnect/*"
IgnorePath "/home/davi/.config/menus/*"
IgnorePath "/home/davi/.config/nchat/color.conf"
IgnorePath "/home/davi/.config/nchat/debug.info"
IgnorePath "/home/davi/.config/nchat/emojis/*"
IgnorePath "/home/davi/.config/nchat/history/*"
IgnorePath "/home/davi/.config/nchat/key.conf"
IgnorePath "/home/davi/.config/nchat/log.txt*"
IgnorePath "/home/davi/.config/nchat/profiles/*"
IgnorePath "/home/davi/.config/nchat/temp"
IgnorePath "/home/davi/.config/nchat/version"
IgnorePath "/home/davi/.config/ngrok/ngrok.yml"
IgnorePath "/home/davi/.config/nvim/.git/*"
IgnorePath "/home/davi/.config/obsidian/*"
IgnorePath "/home/davi/.config/pulse/cookie"
IgnorePath "/home/davi/.config/pypoetry/*"
IgnorePath "/home/davi/.config/qBittorrent/categories.json"
IgnorePath "/home/davi/.config/qBittorrent/ipc-socket"
IgnorePath "/home/davi/.config/qBittorrent/lockfile"
IgnorePath "/home/davi/.config/qBittorrent/qBittorrent-data.conf"
IgnorePath "/home/davi/.config/qBittorrent/qBittorrent.conf"
IgnorePath "/home/davi/.config/qBittorrent/rss/feeds.json"
IgnorePath "/home/davi/.config/qBittorrent/rss/storage.lock"
IgnorePath "/home/davi/.config/qBittorrent/watched_folders.json"
IgnorePath "/home/davi/.config/qalculate/qalc.history"
IgnorePath "/home/davi/.config/sourcery/*"
IgnorePath "/home/davi/.config/yazi/keymap.toml-*" 
IgnorePath "/home/davi/.dotnet/*"
IgnorePath "/home/davi/.gnupg/*"
IgnorePath "/home/davi/.gradle/*" # Came with Logisim-evolution
IgnorePath "/home/davi/.java/*"   # Came with Logisim-evolution
IgnorePath "/home/davi/.local/bin/*"
IgnorePath "/home/davi/.local/lib"
IgnorePath "/home/davi/.local/share/CMakeTools/*"
IgnorePath "/home/davi/.local/share/Hubstaff/*"
IgnorePath "/home/davi/.local/share/Trash/*"
IgnorePath "/home/davi/.local/share/Zeal/*"
IgnorePath "/home/davi/.local/share/applications/*"
IgnorePath "/home/davi/.local/share/auto-battery-notify-state.txt"
IgnorePath "/home/davi/.local/share/claude/*"
IgnorePath "/home/davi/.local/share/easyeffects/*"
IgnorePath "/home/davi/.local/share/flatpak/*"
IgnorePath "/home/davi/.local/share/gegl-0.4/plug-ins"
IgnorePath "/home/davi/.local/share/gvfs-metadata"
IgnorePath "/home/davi/.local/share/hyprland/*"
IgnorePath "/home/davi/.local/share/iwctl"
IgnorePath "/home/davi/.local/share/kpeoplevcard/*"
IgnorePath "/home/davi/.local/share/man"
IgnorePath "/home/davi/.local/share/mime/*"
IgnorePath "/home/davi/.local/share/nvim/*"
IgnorePath "/home/davi/.local/share/pipx/*"
IgnorePath "/home/davi/.local/share/pypoetry/*"
IgnorePath "/home/davi/.local/share/qBittorrent/BT_backup/*"
IgnorePath "/home/davi/.local/share/qBittorrent/GeoDB/dbip-country-lite.mmdb"
IgnorePath "/home/davi/.local/share/qBittorrent/logs/*"
IgnorePath "/home/davi/.local/share/qBittorrent/rss/articles"
IgnorePath "/home/davi/.local/share/qalculate/*"
IgnorePath "/home/davi/.local/share/qmlls/*"
IgnorePath "/home/davi/.local/share/recently-used.xbel"
IgnorePath "/home/davi/.local/share/rofi/rofi_calc_history"
IgnorePath "/home/davi/.local/share/sddm/*"
IgnorePath "/home/davi/.local/share/sourcery/*"
IgnorePath "/home/davi/.local/share/user-places.xbel"
IgnorePath "/home/davi/.local/share/user-places.xbel.bak"
IgnorePath "/home/davi/.local/share/user-places.xbel.tbcache"
IgnorePath "/home/davi/.local/share/uv"
IgnorePath "/home/davi/.local/share/virtualenv/*"
IgnorePath "/home/davi/.local/state/*"
IgnorePath "/home/davi/.local/state/kdeconnect.appstaterc"
IgnorePath "/home/davi/.local/state/lazygit/*"
IgnorePath "/home/davi/.local/state/lesshst"
IgnorePath "/home/davi/.local/state/nvim/*"
IgnorePath "/home/davi/.local/state/paru/*"
IgnorePath "/home/davi/.local/state/pipx/log/*"
IgnorePath "/home/davi/.local/state/qalculate/qalc.history"
IgnorePath "/home/davi/.local/state/syncthing/*"
IgnorePath "/home/davi/.local/state/wireplumber/*"
IgnorePath "/home/davi/.local/state/yazi/.dds" 
IgnorePath "/home/davi/.m2/*"
IgnorePath "/home/davi/.mozilla/*"
IgnorePath "/home/davi/.npm/*"
IgnorePath "/home/davi/.pki/*"
IgnorePath "/home/davi/.python_history"
IgnorePath "/home/davi/.streamlit/*"
IgnorePath "/home/davi/.vscode/*"
IgnorePath "/home/davi/.wdm"
IgnorePath "/home/davi/.wget-hsts"
IgnorePath "/home/davi/.zen/*"
IgnorePath "/home/davi/Documents/*"
IgnorePath "/home/davi/Downloads"
IgnorePath "/home/davi/Downloads/*"
IgnorePath "/home/davi/Games/terminal-doom/.git/*"
IgnorePath "/home/davi/Games/terminal-doom/.gitignore"
IgnorePath "/home/davi/Games/terminal-doom/.zig-cache/*"
IgnorePath "/home/davi/Games/terminal-doom/README.md"
IgnorePath "/home/davi/Games/terminal-doom/build.zig"
IgnorePath "/home/davi/Games/terminal-doom/build.zig.zon"
IgnorePath "/home/davi/Games/terminal-doom/doom1.wad"
IgnorePath "/home/davi/Games/terminal-doom/licenses/*"
IgnorePath "/home/davi/Games/terminal-doom/sound/*"
IgnorePath "/home/davi/Games/terminal-doom/src/*"
IgnorePath "/home/davi/Hubstaff/*"
IgnorePath "/home/davi/Movies"
IgnorePath "/home/davi/Movies/*"
IgnorePath "/home/davi/Phone"
IgnorePath "/home/davi/Pictures/*"
IgnorePath "/home/davi/go"
IgnorePath "/home/davi/nltk_data/*"

# Root
# ====

IgnorePath "/boot/EFI/*"
IgnorePath "/boot/System\ Volume\ Information"
IgnorePath "/boot/amd-ucode.img"
IgnorePath "/boot/grub/fonts"
IgnorePath "/boot/grub/grub.cfg"
IgnorePath "/boot/grub/grubenv"
IgnorePath "/boot/grub/locale/*"
IgnorePath "/boot/grub/themes/minegrub/cache/*"
IgnorePath "/boot/grub/themes/starfield/*"
IgnorePath "/boot/grub/x86_64-efi/*"
IgnorePath "/boot/initramfs-linux-fallback.img"
IgnorePath "/boot/initramfs-linux-lts-fallback.img"
IgnorePath "/boot/initramfs-linux-lts.img"
IgnorePath "/boot/initramfs-linux.img"
IgnorePath "/boot/vmlinuz-linux"
IgnorePath "/boot/vmlinuz-linux-lts"
IgnorePath "/etc/.pwd.lock"
IgnorePath "/etc/.updated"
IgnorePath "/etc/adjtime"
IgnorePath "/etc/audisp"
IgnorePath "/etc/audisp/*"
IgnorePath "/etc/audit/"
IgnorePath "/etc/audit/*"
IgnorePath "/etc/ca-certificates/*"
IgnorePath "/etc/cni/*"
IgnorePath "/etc/cron.d/*"
IgnorePath "/etc/fonts/*"
IgnorePath "/etc/fstab"
IgnorePath "/etc/group"
IgnorePath "/etc/group-"
IgnorePath "/etc/gshadow"
IgnorePath "/etc/gshadow-"
IgnorePath "/etc/hostname"
IgnorePath "/etc/ld.so.cache"
IgnorePath "/etc/locale.conf"
IgnorePath "/etc/locale.gen"
IgnorePath "/etc/localtime"
IgnorePath "/etc/machine-id"
IgnorePath "/etc/mkinitcpio.d/*"
IgnorePath "/etc/os-release"
IgnorePath "/etc/pacman.d/*"
IgnorePath "/etc/passwd"
IgnorePath "/etc/passwd-"
IgnorePath "/etc/passwd.OLD"
IgnorePath "/etc/resolv.conf"
IgnorePath "/etc/shadow"
IgnorePath "/etc/shadow-"
IgnorePath "/etc/shells"
IgnorePath "/etc/ssh/*"
IgnorePath "/etc/ssl/*"
IgnorePath "/etc/subgid"
IgnorePath "/etc/subgid-"
IgnorePath "/etc/subuid"
IgnorePath "/etc/subuid-"
IgnorePath "/etc/sudoers"
IgnorePath "/etc/userdb"
IgnorePath "/etc/vconsole.conf"
IgnorePath "/opt/containerd/*"
IgnorePath "/swap/*"
IgnorePath "/usr/bin/*"
IgnorePath "/usr/lib/*"
IgnorePath "/usr/share/applications/mimeinfo.cache"
IgnorePath "/usr/share/glib-2.0/*"
IgnorePath "/usr/share/icons/*"
IgnorePath "/usr/share/info/*"
IgnorePath "/usr/share/mime/*"
IgnorePath "/var/.updated"
IgnorePath "/var/db/*"
IgnorePath "/var/lib/bluetooth/*"
IgnorePath "/var/lib/containerd/*"
IgnorePath "/var/lib/dbus/*"
IgnorePath "/var/lib/docker/*"
IgnorePath "/var/lib/iwd/.known_network.freq"
IgnorePath "/var/lib/lastlog/*"
IgnorePath "/var/lib/libuuid"
IgnorePath "/var/lib/machines"
IgnorePath "/var/lib/os-prober/*"
IgnorePath "/var/lib/pacman/*"
IgnorePath "/var/lib/portables"
IgnorePath "/var/lib/postgres/*"
IgnorePath "/var/lib/private"
IgnorePath "/var/lib/qbittorrent"
IgnorePath "/var/lib/sbctl/*"
IgnorePath "/var/lib/sddm/*"
IgnorePath "/var/lib/systemd/*"
IgnorePath "/var/lib/texmf/*"
IgnorePath "/var/lib/tpm2-tss/*"
IgnorePath "/var/lib/upower/*"
IgnorePath "/var/log/*"
IgnorePath "/var/tmp/*"
