# Hyprland Windowrules
# ====================
# Reference: https://wiki.hyprland.org/Configuring/Window-Rules/
# Reference:  https://wiki.hyprland.org/Configuring/Workspace-Rules/
# Use `hyprctl clients` to see the windows

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus, class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# To open these on specific workspaces 
windowrule = workspace 10 silent, class:obsidian
windowrule = workspace 1 silent, class:zen

# Usually for youtube videos
windowrule = float, title:Picture-in-Picture
windowrule = pin, title:Picture-in-Picture
windowrule = size 35% 35s%, title:Picture-in-Picture
windowrule = move 100%-w-10% 100%-w-10%, title:Picture-in-Picture
windowrule = keepaspectratio, title:Picture-in-Picture

# For opening Digital in tiling mode
windowrule = tile, title:Digital

# For opening Logisim-evolution in tiling mode
windowrule = tile, class:com-cburch-logisim-Main

# For opening mvi (mpv with scripts for acting as image viewer) in tiling mode
windowrule = float, class:mvi

# For the qualculate app to open as a floting window with some cool features
windowrule = float, initialTitle:Qalculate!
windowrule = pin, initialTitle:Qalculate!
windowrule = opacity 1.0 0.5, initialTitle:Qalculate!
windowrule = noblur, initialTitle:Qalculate!
# The settings bellow are used to center the window on the right half of the screen.
# The formula is:
# size: a%        b%
# move: (b/2+25)% (a/2)%
windowrule = size 30% 70%, initialTitle:Qalculate!
windowrule = move 60% 15%, initialTitle:Qalculate!

