# Hyprland Windowrules
# ====================
# Reference: https://wiki.hyprland.org/Configuring/Window-Rules/
# Reference:  https://wiki.hyprland.org/Configuring/Workspace-Rules/
# Use `hyprctl clients` to see the windows


# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Open browser on the first workspace
windowrule {
  name = windowrule-3
  workspace = 1 silent
  match:class = zen
}


# Usually for Youtube videos. Make  them floating and pinned
windowrule {
  name = windowrule-4
  float = on
  pin = on
  size = (monitor_w*0.35) (monitor_h*0.35)
  move = ((monitor_w*1)-window_w-(monitor_w*0.1)) ((monitor_h*1)-window_h-(monitor_h*0.1))
  keep_aspect_ratio = on
  match:title = Picture-in-Picture
}


# For opening mvi (mpv with scripts for acting as image viewer) in floating mode
windowrule {
  name = windowrule-7
  float = on
  match:class = mvi
}


# For the qualculate app to open as a floting window with some cool features
# The settings bellow are used to center the window on the right half of the screen.
# The formula is:
# size: a%        b%
# move: (b/2+25)% (a/2)%
windowrule {
  name = windowrule-8
  float = on
  pin = on
  opacity = 1.0 0.5
  no_blur = on
  size = (monitor_w*0.3) (monitor_h*0.7)
  move = ((monitor_w*0.6)) ((monitor_h*0.15))
  match:initial_title = Qalculate!
}


# For opening custom terminals on specific workspaces.
# These classes are defined when opening the terminal sessions using the kitty
# command. You can find some of these on `hyprland-autostart.sh` file
windowrule {
  name = windowrule-9
  workspace = 9 silent
  match:class = nchat
}
windowrule {
  name = windowrule-10
  workspace = 10 silent
  match:class = obsidian_tui
}

# Prevent Bisq tooltips from stealing focus, causing an loop of tooltips
# spawning and vanishing.
windowrule {
    name = windowrule-11
    match:class = ^(bisq\.desktop_app\.JavaFXApplication)$
    match:title = ^$
    no_initial_focus = on 
}

# Make the specific bluetui_float terminal class float
windowrule {
    name = windowrule-12
    match:class = ^(bluetui_float)$
    float = on
    size = 800 500
    center = on
}

# Make the specific impala_float terminal class float
windowrule {
    name = windowrule-13
    match:class = ^(impala_float)$
    float = on
    size = 800 500
    center = on
}

