# Hyprland Autostart
# ==================
# Reference: https://wiki.hyprland.org/Configuring/Keywords/#executing
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# This will only call the autostart script. All configurations must be done in the
# bash script.

exec-once = bash ~/.config/hypr/hyprland-autostart.sh

# When using other window managers alongside with hyprland they can overide this
# environment variable. It is good to set this everytime hyprland starts to prevent
# any errors.
env = XDG_CURRENT_DESKTOP,Hyprland
