general {
    hide_cursor = true
    ignore_empty_input = true
}

# This removes the "start" animation. This makes hyprlock blur (or other action) complete
# before sleeping. Otherwise, the blur would not be complete before the computer sleeps,
# thus making it possible to see the screen content for a second after waiking up.
animation = fadeIn, 0, 1.8, linear 

# Make the field animation half the "fail-timeout"
animation = inputFieldColors, 1, 2.5, linear

background {
    #path = screenshot
    color = 0xff000000
    blur_size = 4
    blur_passes = 3
}

input-field {
    size = 300, 50 
    outline_thickness = 0
    #fade_on_empty = true
    fade_on_empty = false
    font_family = Atkinson Next NF
    placeholder_text = Input Password
    fail_text = 
    inner_color = 0xffdeddda #rgba(200, 200, 200, 0.8)
    check_color = 0xffdeddda #rgba(255, 255, 255, 0.9)
    fail_timeout = 500
    rounding = 0
    halign = center
    valign = center
}
