source = ~/.config/hypr/catppuccin-mocha.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

# This removes the "start" animation. This makes hyprlock blur (or other action) complete
# before sleeping. Otherwise, the blur would not be complete before the computer sleeps,
# thus making it possible to see the screen content for a second after waiking up.
animation = fadeIn, 0, 1.8, linear 

# Make the field animation half the "fail-timeout"
animation = inputFieldColors, 1, 2.5, linear

background {
    color = $mantle
    blur_size = 4
    blur_passes = 3
}

input-field {
    size = 300, 50 
    rounding = 0
    halign = center
    valign = center
    outline_thickness = 1
    outer_color = $sapphire

    fade_on_empty = false

    font_family = Atkinson Next NF
    font_color = $text

    placeholder_text = Input Password

    fail_text = 
    fail_color = $red
    fail_timeout = 500

    inner_color = $surface0
    check_color = $surface0
    }
